# ADC-A DATA IO standard

set_property PACKAGE_PIN C15 [get_ports {adc_a_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_os[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_os[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_os[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_a_data[0]}]

# ADC-B DATA IO standard

set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_os[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_os[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_b_os[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_busy]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_convst]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_cs]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_mode_sel]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_range]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_rd]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_reset]
set_property IOSTANDARD LVCMOS33 [get_ports adc_b_stby]

#set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_50m_pin]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN B15 [get_ports {adc_a_data[14]}]
set_property PACKAGE_PIN F16 [get_ports {adc_a_data[13]}]
set_property PACKAGE_PIN E16 [get_ports {adc_a_data[12]}]
set_property PACKAGE_PIN D16 [get_ports {adc_a_data[11]}]
set_property PACKAGE_PIN B16 [get_ports {adc_a_data[10]}]
set_property PACKAGE_PIN E17 [get_ports {adc_a_data[9]}]
set_property PACKAGE_PIN D17 [get_ports {adc_a_data[8]}]
set_property PACKAGE_PIN B17 [get_ports {adc_a_data[7]}]
set_property PACKAGE_PIN F18 [get_ports {adc_a_data[6]}]
set_property PACKAGE_PIN E18 [get_ports {adc_a_data[5]}]
set_property PACKAGE_PIN C18 [get_ports {adc_a_data[4]}]
set_property PACKAGE_PIN B18 [get_ports {adc_a_data[3]}]
set_property PACKAGE_PIN D19 [get_ports {adc_a_data[2]}]
set_property PACKAGE_PIN C19 [get_ports {adc_a_data[1]}]
set_property PACKAGE_PIN G21 [get_ports {adc_a_data[0]}]
set_property PACKAGE_PIN F14 [get_ports {adc_a_os[2]}]
set_property PACKAGE_PIN F13 [get_ports {adc_a_os[1]}]
set_property PACKAGE_PIN F15 [get_ports {adc_a_os[0]}]
set_property PACKAGE_PIN E21 [get_ports adc_a_busy]
set_property PACKAGE_PIN B22 [get_ports adc_a_convst]
set_property PACKAGE_PIN D21 [get_ports adc_a_cs]
set_property PACKAGE_PIN F20 [get_ports adc_a_first_data]
set_property PACKAGE_PIN F19 [get_ports adc_a_mode_sel]
set_property PACKAGE_PIN E14 [get_ports adc_a_range]
set_property PACKAGE_PIN C22 [get_ports adc_a_rd]
set_property PACKAGE_PIN F21 [get_ports adc_a_reset]
set_property PACKAGE_PIN D15 [get_ports adc_a_stby]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_busy]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_convst]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_cs]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_mode_sel]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_range]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_rd]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_reset]
set_property IOSTANDARD LVCMOS33 [get_ports adc_a_stby]

set_property LOC GTPE2_CHANNEL_X0Y7 [get_cells {vuprs_block_design_i/xdma_0/inst/vuprs_block_design_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property PACKAGE_PIN D9 [get_ports {pcie_mgt_rxp[0]}]
set_property PACKAGE_PIN D7 [get_ports {pcie_mgt_txp[0]}]

set_property LOC GTPE2_CHANNEL_X0Y6 [get_cells {vuprs_block_design_i/xdma_0/inst/vuprs_block_design_xdma_0_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtp_channel.gtpe2_channel_i}]
set_property PACKAGE_PIN B10 [get_ports {pcie_mgt_rxp[1]}]
set_property PACKAGE_PIN B6 [get_ports {pcie_mgt_txp[1]}]

set_property PACKAGE_PIN W11 [get_ports {adc_b_data[15]}]
set_property PACKAGE_PIN W12 [get_ports {adc_b_data[14]}]
set_property PACKAGE_PIN V13 [get_ports {adc_b_data[13]}]
set_property PACKAGE_PIN T14 [get_ports {adc_b_data[12]}]
set_property PACKAGE_PIN V14 [get_ports {adc_b_data[11]}]
set_property PACKAGE_PIN V15 [get_ports {adc_b_data[10]}]
set_property PACKAGE_PIN W15 [get_ports {adc_b_data[9]}]
set_property PACKAGE_PIN T15 [get_ports {adc_b_data[8]}]
set_property PACKAGE_PIN W16 [get_ports {adc_b_data[7]}]
set_property PACKAGE_PIN U15 [get_ports {adc_b_data[6]}]
set_property PACKAGE_PIN Y12 [get_ports {adc_b_data[5]}]
set_property PACKAGE_PIN AB12 [get_ports {adc_b_data[4]}]
set_property PACKAGE_PIN AA13 [get_ports {adc_b_data[3]}]
set_property PACKAGE_PIN AB13 [get_ports {adc_b_data[2]}]
set_property PACKAGE_PIN AA14 [get_ports {adc_b_data[1]}]
set_property PACKAGE_PIN AA15 [get_ports {adc_b_data[0]}]
set_property PACKAGE_PIN AB10 [get_ports {adc_b_os[2]}]
set_property PACKAGE_PIN AA10 [get_ports {adc_b_os[1]}]
set_property PACKAGE_PIN AA9 [get_ports {adc_b_os[0]}]
set_property PACKAGE_PIN AA16 [get_ports adc_b_busy]
set_property PACKAGE_PIN AB17 [get_ports adc_b_convst]
set_property PACKAGE_PIN AB16 [get_ports adc_b_cs]
set_property PACKAGE_PIN AB15 [get_ports adc_b_first_data]
set_property PACKAGE_PIN AA11 [get_ports adc_b_mode_sel]
set_property PACKAGE_PIN Y13 [get_ports adc_b_range]
set_property PACKAGE_PIN Y17 [get_ports adc_b_rd]
set_property PACKAGE_PIN W10 [get_ports adc_b_reset]
set_property PACKAGE_PIN V10 [get_ports adc_b_stby]

#set_property PACKAGE_PIN Y18 [get_ports adc_clk_50m_pin]
set_property PACKAGE_PIN F6 [get_ports {pcie_ref_clk_p[0]}]
set_property PACKAGE_PIN A18 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_lnk_up]
set_property PACKAGE_PIN P16 [get_ports pcie_lnk_up]
set_property PULLUP true [get_ports sys_rst_n]

# SPI Flash

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
#set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property PACKAGE_PIN A20 [get_ports adc_card_present]
set_property IOSTANDARD LVCMOS33 [get_ports adc_card_present]
set_property PULLUP true [get_ports adc_card_present]
set_property IOSTANDARD LVCMOS33 [get_ports fpga_adc_card_present_led]
set_property PACKAGE_PIN N14 [get_ports fpga_sampling_led]
set_property PACKAGE_PIN N13 [get_ports fpga_adc_card_present_led]
set_property IOSTANDARD LVCMOS33 [get_ports fpga_sampling_led]

set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[13]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[12]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[11]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[10]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[9]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[8]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[7]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[6]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[5]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[4]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[3]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[2]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[1]}]
set_property IOSTANDARD SSTL135 [get_ports {ddr3_addr[0]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddr3_ck_n[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_in]
set_property PACKAGE_PIN Y18 [get_ports adc_clk_in]

set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
